FROM python:3.13-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add netcat-openbsd python3-dev libffi-dev gcc musl-dev make && rm -rf /var/cache/apk/*

COPY ./requirements.txt .
RUN chmod +x ./requirements.txt
RUN pip install -r ./requirements.txt

COPY ./entrypoint.sh .

COPY . .

RUN ["chmod", "+x", "/usr/src/app/entrypoint.sh"]
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
