"""
Django settings for p_pm_rapi project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.crypto import get_random_string
from datetime import date
from corsheaders.defaults import default_headers
from datetime import timedelta


# if not os.path.exists("logs"):
#     os.makedirs("logs")

# reading .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROJECT_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
PROJECT_NAME = os.path.basename(PROJECT_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# if os.getenv("MODE").lower() == "PROD" else os.getenv("DJANGO_DEBUG")
DEBUG = False

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "cuser",
    "a_pm_rapi",
    "django_filters",
    "rest_framework",
    "corsheaders",
    "a_logs.apps.ALogsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Your Middleware Goes Here
]

ROOT_URLCONF = "p_pm_rapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            TEMPLATE_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "p_pm_rapi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# loging

# loging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname}; {asctime}; {module}; {process:d}; {thread:d}; {message};",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        # "file": {
        #     "level": "DEBUG",
        #     # 'class': 'logging.FileHandler',
        #     "class": "logging.handlers.TimedRotatingFileHandler",
        #     "when": "midnight",  # 'midnight', # daily, you can use 'midnight' as well
        #     "filename": os.path.join(
        #         BASE_DIR,
        #         f'logs/pm-debug-log-new-{get_random_string(length=3)}-{date.today().strftime("%Y%m%d") }.csv',
        #     ),
        #     "formatter": "verbose",
        # },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],  # "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/api/static/"

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "static"),
    # os.path.join(BASE_DIR, "ui", "static"),
]

# PROJECT_ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
PROJECT_ROOT_DIR = os.path.dirname(os.path.abspath("requirements.txt"))
STATIC_ROOT = os.path.join(PROJECT_ROOT_DIR, "staticfiles")
print("STATIC_ROOT(static collection path): ", STATIC_ROOT)

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_ROOT = os.path.join(PROJECT_ROOT_DIR, "mediafiles")
MEDIA_URL = "/api/media/"

# Application custom configuration
ACCOUNTS_HOST = os.environ.get("AUTH_HOST")
AUTH_HOST = os.environ.get("AUTH_HOST")
CALENDAR_HOST = os.environ.get("CALENDAR_HOST")
NOTIFICATION_HOST = os.environ.get("NOTIFICATION_HOST")
PM_HOST = os.getenv("PM_HOST")

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

# django-username-email
AUTH_USER_MODEL = "cuser.CUser"


#### REST FRAMEWORK STUFF #####
MIGRATE = os.getenv("MIGRATE", False)
REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': 'authentication.CustomUser',
    # 'DATE_INPUT_FORMATS': ["%m/%d/%Y",],
    # 'DATE_FORMAT': "%m/%d/%Y",
    # 'DATETIME_FORMAT': "%m/%d/%Y, %H:%M:%S %p",
    # 'DATETIME_INPUT_FORMATS': ["%m/%d/%Y, %H:%M:%S %p",],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": ["authentication.APIAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": [
        # 'rest_framework.permissions.IsAuthenticated',
        "a_pm_rapi.permissions.GlobalViewPermission"
    ],
    "DEFAULT_FILTER_BACKENDS": ["a_pm_rapi.api.filters.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "a_pm_rapi.api.paginations.CustomPagination",
    "EXCEPTION_HANDLER": 'p_pm_rapi.utils.exception_handler.custom_exception_handler'
}


MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")

AUTH_HOST = os.getenv("AUTH_HOST")

RAPI_HOST = os.getenv("RAPI_HOST")

CRM_HOST = os.getenv("CRM_HOST")
CRM_V2_HOST = os.getenv("CRM_V2_HOST")

DRIVE_HOST = os.getenv("DRIVE_HOST")
BPA_HOST = os.getenv("BPA_HOST")
HR_HOST = os.getenv("HR_HOST")
SYSTEM_HOST = os.getenv("SYSTEM_HOST")


CORS_HOSTS = os.getenv("CORS_HOSTS", "pullstream.com").split(",")
CORS_ALLOWED_ORIGIN_REGEXES = [
    rf'^http://(localhost|127.0.0.1)(:\d+)?$',
    rf'^http://(pm-rapi)(:\d+)?$',
    *list(map(lambda domain: rf'^(https?://)?(?:[\w-]+\.)*{domain}$', CORS_HOSTS))
]

CSRF_TRUSTED_ORIGINS = ['https://*.pullstream.com', 'http://127.0.0.1']
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ActAs",
    "Application-Authorization",
    "X-Timezone",
]

# Celery Stuff
BROKER_URL = os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL")
CELERY_ACCEPT_CONTENT = os.getenv("CELERY_ACCEPT_CONTENT", "").split()
CELERY_TASK_SERIALIZER = os.getenv("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = os.getenv("CELERY_RESULT_SERIALIZER")
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")

CELERY_LONGTERM_SCHEDULER_BACKEND = os.getenv("REDIS_URL")

CELERY_BEAT_SCHEDULE = {
    'run-every-1-minutes': {
        'task': f'{PROJECT_NAME}.celery.run_celery_long_term',
        'schedule': timedelta(minutes=1),
        'args': (),
        'options': {},
    },
}

MS_NAME = os.getenv("MS_NAME")
LOGGING_HOST = os.getenv("LOGGING_HOST")

# UUID_KEY_VALUE_PAIR = {
#     # "created_by" : f"{AUTH_HOST}accounts/profiles/", # param id
#     "user": f"{AUTH_HOST}accounts/users",  # param id
#     "responsible": f"{HR_HOST}employees",  # param id
#     # "updated_by" : f"{AUTH_HOST}accounts/profiles/",
#     # "company" : f"{CRM_HOST}companies/",
#     "person" : f"{CRM_HOST}persons",
# }

UUID_KEY_VALUE_PAIR = {
    "user": {"model": "user", "host": f"{AUTH_HOST}v1/"},
    "responsible": {"model": "Employee", "host": HR_HOST},
    "person": {"model": "person", "host": f"{CRM_V2_HOST}v1/"},
}


MICROSERVICE_KEY_VALUE_PAIR = {
    "HR": {
        "Vacancy": f"{HR_HOST}vacancies",
        "RecruitmentPipelineStages": f"{HR_HOST}recruitment-pipeline-stages",
        "Candidate": f"{HR_HOST}candidates",
    },
    "PM": {
        "Task": f"{PM_HOST}tasks",
        "TaskStatus": f"{PM_HOST}task-status",
    },
}

PULLSTREAM_CLIENT_ID = "88a11494-2185-4338-b1d1-aec4b11537c0"

INTERNAL_NETWORK = os.getenv("INTERNAL_NETWORK", "127.0.0.1")

IS_LOCAL = os.getenv("IS_LOCAL", False)
