// @gen:AUTO_GENERATED - This file is generated by compute-rapi
// apps/@gen{MICROSERVICE_SLUG}/src/components/GenericDetailPage.tsx
'use client';

import React, { useState, useEffect, ComponentType } from 'react';
import PageTitle from '@ps/shared-core/ui/PageTitle';
import { EntityConfig } from '@/config/entityRegistry';

export interface GenericDetailPageProps {
  entityConfig: EntityConfig;
  entitySlug: string;
}

/**
 * Generic detail page component that dynamically loads and renders
 * the entity-specific DetailCore component with its DetailForm.
 *
 * The DetailCore component contains all the related tabs (child entity tables)
 * that are generated based on the model's relationships.
 */
export default function GenericDetailPage({
  entityConfig,
  entitySlug,
}: GenericDetailPageProps) {
  // Dynamic component loading
  const [DetailCoreComponent, setDetailCoreComponent] = useState<ComponentType<any> | null>(null);
  const [DetailFormComponent, setDetailFormComponent] = useState<ComponentType<any> | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  // Load both DetailCore and DetailForm components
  useEffect(() => {
    let mounted = true;

    async function loadComponents() {
      try {
        const [coreMod, formMod] = await Promise.all([
          entityConfig.DetailCore(),
          entityConfig.DetailForm(),
        ]);

        if (mounted) {
          if (!coreMod.default) {
            // No DetailCore available - this entity doesn't have a detail page
            setLoadError(`No detail page available for ${entityConfig.label}`);
          } else {
            setDetailCoreComponent(() => coreMod.default);
            setDetailFormComponent(() => formMod.default);
          }
          setIsLoading(false);
        }
      } catch (error) {
        console.error(`Failed to load detail components for ${entitySlug}:`, error);
        if (mounted) {
          setLoadError(`Failed to load ${entityConfig.label} detail page`);
          setIsLoading(false);
        }
      }
    }

    loadComponents();

    return () => {
      mounted = false;
    };
  }, [entityConfig, entitySlug]);

  // Loading state
  if (isLoading) {
    return (
      <>
        <PageTitle title={entityConfig.label} />
        <div style={{ padding: 40, textAlign: 'center' }}>
          Loading {entityConfig.label}...
        </div>
      </>
    );
  }

  // Error state
  if (loadError || !DetailCoreComponent || !DetailFormComponent) {
    return (
      <>
        <PageTitle title={entityConfig.label} />
        <div style={{ padding: 40, textAlign: 'center', color: '#666' }}>
          {loadError || `Unable to load detail page for ${entityConfig.label}`}
        </div>
      </>
    );
  }

  // Render the entity-specific DetailCore component with its DetailForm
  // The DetailCore contains all the model's related tabs (child entity tables)
  return (
    <DetailCoreComponent
      DetailFormComponent={DetailFormComponent}
    />
  );
}
