// @gen:AUTO_GENERATED - This file is generated by compute-rapi
// apps/@gen{MICROSERVICE_SLUG}/src/components/GenericListPage.tsx
'use client';

import React, { useState, useEffect, ReactNode, ComponentType } from 'react';
import { CalendarPlus } from 'lucide-react';
import { toast } from 'react-toastify';
import DataTableV2 from '@ps/shared-core/ui/DataTableV2';
import PageTitle from '@ps/shared-core/ui/PageTitle';
import { getRoute } from '@ps/entity-core/routes';
import { ColumnConfig } from '@ps/shared-core/ui/DataTableV2/TableColumns';
import BulkAddReminder from '@ps/entity-core/calendar/forms/BulkAddReminder/BulkAddReminder';
import {
  REMINDER_ENTITY_MICROSERVICES
} from '@ps/shared-core/config/apps/calendar/constants';
import { EntityConfig } from '@/config/entityRegistry';

// Loading fallback for dynamic components
const FormLoadingFallback = () => (
  <div style={{ padding: 20, textAlign: 'center' }}>Loading form...</div>
);

export interface BulkAction {
  key: string;
  label: string;
  icon?: ReactNode;
  onClick: (ctx: { selectedIds: string[]; searchTerm: string }) => void;
}

export interface GenericListPageProps {
  entityConfig: EntityConfig;
  entitySlug: string;
  additionalBulkActions?: BulkAction[];
  children?: ReactNode;
}

export default function GenericListPage({
  entityConfig,
  entitySlug,
  additionalBulkActions = [],
  children,
}: GenericListPageProps) {
  const [CreateFormComponent, setCreateFormComponent] = useState<ComponentType<any> | null>(null);
  const [columns, setColumns] = useState<ColumnConfig[] | null>(null);
  const [dataMapper, setDataMapper] = useState<((row: any) => any) | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [bulkReminderOpen, setBulkReminderOpen] = useState(false);
  const [bulkCtx, setBulkCtx] = useState<{ ids: string[]; search: string }>({
    ids: [],
    search: '',
  });

  // Load components on mount
  useEffect(() => {
    let mounted = true;

    async function loadComponents() {
      try {
        const [formMod, cols, mapper] = await Promise.all([
          entityConfig.CreateForm(),
          entityConfig.columns(),
          entityConfig.dataMapper(),
        ]);

        if (mounted) {
          setCreateFormComponent(() => formMod.default);
          setColumns(cols);
          setDataMapper(() => mapper);
          setIsLoading(false);
        }
      } catch (error) {
        console.error(`Failed to load components for ${entitySlug}:`, error);
        setIsLoading(false);
      }
    }

    loadComponents();

    return () => {
      mounted = false;
    };
  }, [entityConfig, entitySlug]);

  // Use importModel from entityConfig which contains the correct singular form
  const reminderEntityModel = entityConfig.importModel;

  // Default bulk action for reminders
  const defaultBulkActions: BulkAction[] = [
    {
      key: 'addReminder',
      label: 'Add reminder',
      icon: <CalendarPlus size={14} style={{ marginRight: 8 }} />,
      onClick: ({ selectedIds, searchTerm }) => {
        setBulkCtx({ ids: selectedIds, search: searchTerm });
        setBulkReminderOpen(true);
      },
    },
  ];

  const allBulkActions = [...defaultBulkActions, ...additionalBulkActions];

  if (isLoading || !CreateFormComponent || !columns || !dataMapper) {
    return (
      <>
        <PageTitle title={entityConfig.label} />
        <div style={{ padding: 40, textAlign: 'center' }}>
          Loading {entityConfig.label}...
        </div>
      </>
    );
  }

  return (
    <>
      <PageTitle title={entityConfig.label} />

      {children}

      <BulkAddReminder
        entityMicroservice={REMINDER_ENTITY_MICROSERVICES.@gen{MICROSERVICE_NAME|UPPER_SNAKE}}
        entityModel={reminderEntityModel as any}
        open={bulkReminderOpen}
        setOpen={setBulkReminderOpen}
        selectedIds={bulkCtx.ids}
        searchTerm={bulkCtx.search}
        onSuccess={() => {
          toast.success('Reminder(s) created');
        }}
      />

      <DataTableV2
        title={entityConfig.label}
        helpfulHint={entityConfig.helpfulHint ?? ''}
        queryKey={[`${entitySlug}-list-page`]}
        recordUrl={getRoute(entityConfig.routeKey as any)}
        CreateFormComponent={CreateFormComponent}
        columns={columns}
        renderRow={dataMapper}
        enableColorPicker={true}
        importExportUrls={{
          import: getRoute('@gen{MICROSERVICE_SLUG}/getImportURL')({
            query: entityConfig.importModel,
          }),
          export: getRoute('@gen{MICROSERVICE_SLUG}/getExportURL')({
            query: entityConfig.importModel,
          }),
        }}
        importModel={entityConfig.importModel}
        enableBulkVisibility={true}
        bulkActions={allBulkActions}
      />
    </>
  );
}
