const COMPUTE_GENERATION_QUEUE_NAME = 'computeGenerationQueue';

const DEFAULT_LEADER_TTL_MS = 30000;
const COMPUTE_QUEUE_LEADER_KEY =
  process.env.COMPUTE_QUEUE_LEADER_KEY || 'locks:compute:generate:leader:v1';
const COMPUTE_QUEUE_LEADER_TTL_MS =
  Number(process.env.COMPUTE_QUEUE_LEADER_TTL_MS) || DEFAULT_LEADER_TTL_MS;
const COMPUTE_QUEUE_LEADER_RENEW_MS =
  Number(process.env.COMPUTE_QUEUE_LEADER_RENEW_MS) ||
  Math.max(5000, Math.floor(COMPUTE_QUEUE_LEADER_TTL_MS / 2));

const COMPUTE_QUEUE_STALE_THRESHOLD_MS =
  Number(process.env.COMPUTE_GEN_STALE_THRESHOLD_MS) || 15 * 60 * 1000;

module.exports = {
  COMPUTE_GENERATION_QUEUE_NAME,
  COMPUTE_QUEUE_LEADER_KEY,
  COMPUTE_QUEUE_LEADER_TTL_MS,
  COMPUTE_QUEUE_LEADER_RENEW_MS,
  COMPUTE_QUEUE_STALE_THRESHOLD_MS,
};
