from django.urls import path
from .views import (
    CloneTaskAPIView,
    DuplicateBacklogAPIView,
    BulkConnectTasksToSprintAPIView,
    CloneSystemTemplateAPIView,
    SprintMetaProjectListCreateAPIView,
    SprintMetaProjectRetrieveUpdateDestroyAPIView,
    BulkStageCreateAPIView,
    ProgramListCreateAPIView,
    ProgramRetrieveUpdateDestroyAPIView,
    ProjectListCreateAPIView,
    ProjectRetrieveUpdateDestroyAPIView,
    HlrListCreateAPIView,
    HlrRetrieveUpdateDestroyAPIView,
    SprintMetaListCreateAPIView,
    SprintMetaRetrieveUpdateDestroyAPIView,
    BulkCreateSprintTasksAPIView,
    PersonaRetrieveUpdateDestroyAPIView,
    BacklogListCreateAPIView,
    BacklogRetrieveUpdateDestroyAPIView,
    TaskStatusListCreateAPIView,
    TaskTypeListCreateAPIView,
    TaskTypeRetrieveUpdateDestroyAPIView,
    ResourceListCreateAPIView,
    ResourceRetrieveUpdateDestroyAPIView,
    RoleListCreateAPIView,
    TaskListCreateAPIView,
    TaskRetrieveUpdateDestroyAPIView,
    TaskCommentListCreateAPIView,
    AcceptanceTestListCreateAPIView,
    TaskResourceListCreateAPIView,
    TaskResourceRetrieveUpdateDestroyAPIView,
    StakeholderListCreateAPIView,
    StakeholderRetrieveUpdateDestroyAPIView,
    BugArtifactListCreateAPIView,
    BugArtifactRetrieveUpdateDestroyAPIView,
    ProjectArtifactListCreateAPIView,
    HlrArtifactListCreateAPIView,
    BacklogArtifactListCreateAPIView,
    WorkingTimeListCreateAPIView,
    WorkingTimeRetrieveUpdateDestroyAPIView,
    WorkCodeListCreateAPIView,
    WorkCodeRetrieveUpdateDestroyAPIView,
    TimesheetListCreateAPIView,
    TimesheetRetrieveUpdateDestroyAPIView,
    BugListCreateAPIView,
    BugRetrieveUpdateDestroyAPIView,
    BugCommentListCreateAPIView,
    BugCommentRetrieveUpdateDestroyAPIView,
    SprintMetaBugListCreateAPIView,
    SprintMetaBugRetrieveUpdateDestroyAPIView,
    RoleRetrieveUpdateDestroyAPIView,
    PersonaListCreateAPIView,
    TaskCommentRetrieveUpdateDestroyAPIView,
    BugArtifactRetrieveUpdateDestroyAPIView,
    ProjectArtifactRetrieveUpdateDestroyAPIView,
    HlrArtifactRetrieveUpdateDestroyAPIView,
    BacklogArtifactRetrieveUpdateDestroyAPIView,
    AcceptanceTestRetrieveUpdateDestroyAPIView,
    # ProjectDuplicateView,
    TaskBacklogListCreateAPIView,
    TestsConductedListCreateAPIView,
    SprintTaskListCreateAPIView,
    TaskBugListCreateAPIView,
    TaskBacklogRetrieveUpdateDestroyAPIView,
    TestsConductedRetrieveUpdateDestroyAPIView,
    SprintTaskRetrieveUpdateDestroyAPIView,
    TaskBugRetrieveUpdateDestroyAPIView,
    SprintListCreateAPIView,
    SprintRetrieveUpdateDestroyAPIView,
    TaskStatusAPIView,
    SprintStatusAPIView,
    TaskStatusRetrieveUpdateDestroyAPIView,
    BugStatusListCreateAPIView,
    BugStatusRetrieveUpdateDestroyAPIView,
    BugStatusAPIView,
    AcceptanceStatusListCreateAPIView,
    AcceptanceStatusRetrieveUpdateDestroyAPIView,
    AcceptanceTestStatusAPIView,
    FeatureRequestListCreateAPIView,
    FeatureRequestRetrieveUpdateDestroyAPIView,
    AcceptanceTestProjectUpdateView,
    DeleteAllAPIView,
    MultipleActionAPIView,
    ExportAPIView,
    BulkUpdateTaskStatusAPIView,
    BulkUpdateAcceptanceStatusAPIView,
    BulkUpdateBugStatusAPIView,
    INAListCreateAPIView, INARetrieveUpdateDestroyAPIView, INAAPIView, MeProjectTaskStatusAPIView,
    ExportAPIView,
    ImportActionAPIView,
    GetBulkDetailsAPIView,
    BulkDuplicateAPIView,
    BulkCreateSprintBugsAPIView,
    GetOrderedTaskStatusesAPIView,
    BulkDeleteTaskAPIView,
    BulkCreateHLRsAPIView,
    BulkCreateBacklogsAPIView,
    BulkCreateUATsAPIView,
    BulkCreatePersonaAPIView,
    BulkCreateBugsAPIView,
    # health
    LivenessProbeHealthCheckAPIView,
    ReadinessProbeHealthCheckAPIView,
)


urlpatterns = [
    path(
        "healthz/",
        LivenessProbeHealthCheckAPIView.as_view(),
        name="liveness-probe-health-check",
    ),
    path(
        "health/",
        ReadinessProbeHealthCheckAPIView.as_view(),
        name="readiness-probe-health-check",
    ),
    path("bulk-create-hlrs/", BulkCreateHLRsAPIView.as_view(),
         name="bulk-create-hlrs"),
    path("bulk-create-personas/", BulkCreatePersonaAPIView.as_view(),
         name="bulk-create-personas"),
    path("bulk-create-backlogs/", BulkCreateBacklogsAPIView.as_view(),
         name="bulk-create-backlogs"),
    path("bulk-create-uats/", BulkCreateUATsAPIView.as_view(),
         name="bulk-create-uats"),
    path("bulk-delete-tasks/", BulkDeleteTaskAPIView.as_view(),
         name="bulk-delete-tasks"),
    path("duplicate-task/<uuid:task_id>/", CloneTaskAPIView.as_view(),
         name="duplicate-task"),
    path("duplicate-backlogs/", DuplicateBacklogAPIView.as_view(),
         name="duplicate-backlogs"),
    path("bulk-connect-tasks-to-sprint/", BulkConnectTasksToSprintAPIView.as_view(),
         name="bulk-connect-tasks-to-sprint"),
    path("clone-system-templates/<str:model>/", CloneSystemTemplateAPIView.as_view(),
         name="clone-system-templates"),
    path("clone-system-templates/<str:model>/<uuid:template_id>/", CloneSystemTemplateAPIView.as_view(),
         name="clone-system-templates"),
    path("sprint-meta-projects/", SprintMetaProjectListCreateAPIView.as_view(),
         name="sprint-meta-projects"),
    path(
        "sprint-meta-projects/<uuid:id>/",
        SprintMetaProjectRetrieveUpdateDestroyAPIView.as_view(),
        name="sprint_meta_project_detail",
    ),
    path("programs/", ProgramListCreateAPIView.as_view(), name="programs"),
    path(
        "programs/<uuid:id>/",
        ProgramRetrieveUpdateDestroyAPIView.as_view(),
        name="program_detail",
    ),
    path(
        "projects/",
        ProjectListCreateAPIView.as_view(),
        name="project_list_create_api_view",
    ),
    # path(
    #     "duplicate/project/<uuid:project_id>/",
    #     ProjectDuplicateView.as_view(),
    #     name="duplicate_project",
    # ),
    path(
        "projects/<uuid:id>/",
        ProjectRetrieveUpdateDestroyAPIView.as_view(),
        name="project_detail",
    ),
    path("hlrs/", HlrListCreateAPIView.as_view(),
         name="hlr_list_create_api_view"),
    path(
        "hlrs/<uuid:id>/", HlrRetrieveUpdateDestroyAPIView.as_view(), name="hlr_detail"
    ),
    path(
        "sprint-metas/",
        SprintMetaListCreateAPIView.as_view(),
        name="sprint_list_create_api_view",
    ),
    path(
        "sprint-metas/<uuid:id>/",
        SprintMetaRetrieveUpdateDestroyAPIView.as_view(),
        name="sprint_detail",
    ),
    path(
        "bulk-create-sprint-tasks/<uuid:sprint_id>/",
        BulkCreateSprintTasksAPIView.as_view(),
        name="bulk_create_sprint_task",
    ),
    path(
        "bulk-create-sprint-bugs/",
        BulkCreateSprintBugsAPIView.as_view(),
        name="bulk_create_sprint_bugs",
    ),
    path(
        "bulk-create-bugs/",
        BulkCreateBugsAPIView.as_view(),
        name="bulk_create_bugs",
    ),
    path(
        "personas/",
        PersonaListCreateAPIView.as_view(),
        name="persona_list_create_api_view",
    ),
    path(
        "personas/<uuid:id>/",
        PersonaRetrieveUpdateDestroyAPIView.as_view(),
        name="persona_detail",
    ),
    path(
        "backlogs/",
        BacklogListCreateAPIView.as_view(),
        name="backlog_list_create_api_view",
    ),
    path(
        "backlogs/<uuid:id>/",
        BacklogRetrieveUpdateDestroyAPIView.as_view(),
        name="backlog_detail",
    ),
    path(
        "task-status/",
        TaskStatusListCreateAPIView.as_view(),
        name="task_status_list_create_api_view",
    ),
    path(
        "task-status/<uuid:id>/",
        TaskStatusRetrieveUpdateDestroyAPIView.as_view(),
        name="task_status_retrieve_api_view",
    ),

    path(
        "get-ordered-task-statuses/<uuid:project_id>/",
        GetOrderedTaskStatusesAPIView.as_view(),
        name="ordered-task-statuses",
    ),

    path(
        "bug-status/",
        BugStatusListCreateAPIView.as_view(),
        name="bug_status_list_create_api_view",
    ),
    path(
        "bug-status/<uuid:id>/",
        BugStatusRetrieveUpdateDestroyAPIView.as_view(),
        name="bug_status_retrieve_api_view",
    ),
    path(
        "task-types/",
        TaskTypeListCreateAPIView.as_view(),
        name="task_type_list_create_api_view",
    ),
    path(
        "task-types/<uuid:id>/",
        TaskTypeRetrieveUpdateDestroyAPIView.as_view(),
        name="task_type_detail_api_view",
    ),

    path(
        "resources/",
        ResourceListCreateAPIView.as_view(),
        name="resource_list_create_api_view",
    ),
    path(
        "resources/<uuid:id>/",
        ResourceRetrieveUpdateDestroyAPIView.as_view(),
        name="resource_detail",
    ),
    path("roles/", RoleListCreateAPIView.as_view(),
         name="role_list_create_api_view"),
    path(
        "roles/<uuid:id>/",
        RoleRetrieveUpdateDestroyAPIView.as_view(),
        name="role_detail",
    ),
    path("tasks/", TaskListCreateAPIView.as_view(),
         name="task_list_create_api_view"),
    path(
        "tasks/<uuid:id>/",
        TaskRetrieveUpdateDestroyAPIView.as_view(),
        name="task_detail",
    ),
    path(
        "task-comments/",
        TaskCommentListCreateAPIView.as_view(),
        name="comment_list_create_api_view",
    ),
    path(
        "task-comments/<uuid:id>/",
        TaskCommentRetrieveUpdateDestroyAPIView.as_view(),
        name="comment_detail",
    ),
    path(
        "acceptance-tests/",
        AcceptanceTestListCreateAPIView.as_view(),
        name="acceptance_criteria_list_create_api_view",
    ),
    path(
        "acceptance-tests/<uuid:id>/",
        AcceptanceTestRetrieveUpdateDestroyAPIView.as_view(),
        name="acceptance_criteria_detail",
    ),
    path(
        "acceptance-test-statuses/",
        AcceptanceStatusListCreateAPIView.as_view(),
        name="acceptance_test_status_list_create_api_view",
    ),
    path(
        "acceptance-test-statuses/<uuid:id>/",
        AcceptanceStatusRetrieveUpdateDestroyAPIView.as_view(),
        name="acceptance_test_status_detail",
    ),
    path(
        "task-resources/",
        TaskResourceListCreateAPIView.as_view(),
        name="task_resource_list_create_api_view",
    ),
    path(
        "task-resources/<uuid:id>/",
        TaskResourceRetrieveUpdateDestroyAPIView.as_view(),
        name="task_resource_detail",
    ),
    path(
        "stakeholders/",
        StakeholderListCreateAPIView.as_view(),
        name="stakeholder_list_create_api_view",
    ),
    path(
        "stakeholders/<uuid:id>/",
        StakeholderRetrieveUpdateDestroyAPIView.as_view(),
        name="stakeholder_detail",
    ),
    path(
        "bug-artifacts/",
        BugArtifactListCreateAPIView.as_view(),
        name="bug_artifact_list_create_api_view",
    ),
    path(
        "bug-artifacts/<uuid:id>/",
        BugArtifactRetrieveUpdateDestroyAPIView.as_view(),
        name="artifact_detail",
    ),
    path(
        "project-artifacts/",
        ProjectArtifactListCreateAPIView.as_view(),
        name="project_artifact_list_create_api_view",
    ),
    path(
        "project-artifacts/<uuid:id>/",
        ProjectArtifactRetrieveUpdateDestroyAPIView.as_view(),
        name="project_artifact_retrieve_update_destroy_api_view",
    ),
    path(
        "hlr-artifacts/",
        HlrArtifactListCreateAPIView.as_view(),
        name="hlr_artifact_list_create_api_view",
    ),
    path(
        "hlr-artifacts/<uuid:id>/",
        HlrArtifactRetrieveUpdateDestroyAPIView.as_view(),
        name="hlr_artifact_list_create_api_view",
    ),
    path(
        "backlog-artifacts/",
        BacklogArtifactListCreateAPIView.as_view(),
        name="backlog_artifact_list_create_api_view",
    ),
    path(
        "backlog-artifacts/<uuid:id>/",
        BacklogArtifactRetrieveUpdateDestroyAPIView.as_view(),
        name="backlog_artifact_list_create_api_view",
    ),
    path(
        "working-times/",
        WorkingTimeListCreateAPIView.as_view(),
        name="working_time_list_create_api_view",
    ),
    path(
        "working-times/<uuid:id>/",
        WorkingTimeRetrieveUpdateDestroyAPIView.as_view(),
        name="working_time_detail",
    ),
    path(
        "work-codes/",
        WorkCodeListCreateAPIView.as_view(),
        name="work_code_list_create_api_view",
    ),
    path(
        "work-codes/<uuid:id>/",
        WorkCodeRetrieveUpdateDestroyAPIView.as_view(),
        name="work_code_detail",
    ),
    path(
        "time-sheets/",
        TimesheetListCreateAPIView.as_view(),
        name="timesheet_list_create_api_view",
    ),
    path(
        "time-sheets/<uuid:id>/",
        TimesheetRetrieveUpdateDestroyAPIView.as_view(),
        name="timesheet_detail",
    ),
    path("bugs/", BugListCreateAPIView.as_view(),
         name="bug_list_create_api_view"),
    path(
        "bugs/<uuid:id>/", BugRetrieveUpdateDestroyAPIView.as_view(), name="bug_detail"
    ),
    path(
        "bug-comments/",
        BugCommentListCreateAPIView.as_view(),
        name="bug_comment_list_create_api_view",
    ),
    path(
        "bug-comments/<uuid:id>/",
        BugCommentRetrieveUpdateDestroyAPIView.as_view(),
        name="bug_comment_detail",
    ),
    path(
        "sprint-meta-bugs/",
        SprintMetaBugListCreateAPIView.as_view(),
        name="sprint_bug_list_create_api_view",
    ),
    path(
        "sprint-meta-bugs/<uuid:id>/",
        SprintMetaBugRetrieveUpdateDestroyAPIView.as_view(),
        name="sprint_bug_list_create_api_view",
    ),
    path(
        "task-backlogs/",
        TaskBacklogListCreateAPIView.as_view(),
        name="task_backlog_list_create_api_view",
    ),
    path(
        "task-backlogs/<uuid:id>/",
        TaskBacklogRetrieveUpdateDestroyAPIView.as_view(),
        name="task_backlog_detail_view",
    ),
    path(
        "test-conducteds/",
        TestsConductedListCreateAPIView.as_view(),
        name="test_conducted_list_create_api_view",
    ),
    path(
        "test-conducteds/<uuid:id>/",
        TestsConductedRetrieveUpdateDestroyAPIView.as_view(),
        name="test_conducted_list_create_api_view",
    ),
    path(
        "sprints/",
        SprintListCreateAPIView.as_view(),
        name="sprint_list_create_api_view",
    ),
    path(
        "sprints/<uuid:id>/",
        SprintRetrieveUpdateDestroyAPIView.as_view(),
        name="sprint_list_create_api_view",
    ),
    path(
        "sprint-tasks/",
        SprintTaskListCreateAPIView.as_view(),
        name="sprint_task_list_create_api_view",
    ),
    path(
        "sprint-tasks/<uuid:id>/",
        SprintTaskRetrieveUpdateDestroyAPIView.as_view(),
        name="sprint_task_list_create_api_view",
    ),
    path(
        "task-bugs/",
        TaskBugListCreateAPIView.as_view(),
        name="task-bug_list_create_api_view",
    ),
    path(
        "task-bugs/<uuid:id>/",
        TaskBugRetrieveUpdateDestroyAPIView.as_view(),
        name="task-bug_list_create_api_view",
    ),
    path(
        "feature-requests/",
        FeatureRequestListCreateAPIView.as_view(),
        name="feature_request_list_create_api_view",
    ),
    path(
        "feature-requests/<uuid:id>/",
        FeatureRequestRetrieveUpdateDestroyAPIView.as_view(),
        name="feature_request_retrieve_update_destroy_api_view",
    ),
    path(
        "update-project-uats/",
        AcceptanceTestProjectUpdateView.as_view(),
        name="acceptance_test_project_update_view",
    ),
    path('inas/', INAListCreateAPIView.as_view(),
         name="ina_list_create_view"),

    path('inas/<uuid:id>/', INARetrieveUpdateDestroyAPIView.as_view(),
         name="ina_detail"),

    path("ina-stages/", INAAPIView.as_view(), name="ina_stages"),
    path("me-project-task-stages/", MeProjectTaskStatusAPIView.as_view(),
         name="me_project_task_stages"),
    path("task-stages/", TaskStatusAPIView.as_view(), name="task_stages"),
    path("sprint-stages/", SprintStatusAPIView.as_view(), name="task_stages"),
    path("bug-stages/", BugStatusAPIView.as_view(), name="bug_stages"),
    path("uats-stages/", AcceptanceTestStatusAPIView.as_view(), name="uats_stages"),


    path("bulk-update-task-status/", BulkUpdateTaskStatusAPIView.as_view(),
         name="bulk_task_status_update"),
    path("bulk-update-acceptance-status/", BulkUpdateAcceptanceStatusAPIView.as_view(),
         name="bulk_acceptance_status_update"),
    path("bulk-update-bug-status/", BulkUpdateBugStatusAPIView.as_view(),
         name="bulk_bug_status_update"),
    path("delete-all/", DeleteAllAPIView.as_view(), name="delete_all"),
    # path("multiple-actions/", MultipleActionAPIView.as_view(),
    #      name="multiple_actions"),
    path(
        "export/<str:model_name>/",
        ExportAPIView.as_view(),
        name="export",
    ),
    path(
        "import/<str:model_name>/",
        ImportActionAPIView.as_view(),
        name="import",
    ),

    path(
        "bulk-create-stages/<uuid:project_id>/",
        BulkStageCreateAPIView.as_view(),
        name="bulk_stages",
    ),

    path(
        "bulk-duplicate/",
        BulkDuplicateAPIView.as_view(),
        name="bulk_duplicate",
    ),
    path('get-bulk-details/', GetBulkDetailsAPIView.as_view(),
         name="get_bulk_details"),

]
