// @gen:AUTO_GENERATED - This file is generated by compute-rapi
// apps/@gen{MICROSERVICE_SLUG}/src/pages/[listType]/index.tsx
import { GetServerSidePropsContext } from 'next';
import withProtectedV2 from '@ps/shared-core/config/withProtectedV2';
import GenericListPage from '@/components/GenericListPage';
import { getEntityConfig, isValidEntitySlug } from '@/config/entityRegistry';
import ErrorPage from '@ps/shared-core/ui/ErrorPage';

interface ListPageProps {
  listType: string;
  isValid: boolean;
}

export const getServerSideProps = withProtectedV2(
  async (context: GetServerSidePropsContext) => {
    const listType = context.params?.listType as string;
    const isValid = isValidEntitySlug(listType);

    if (!isValid) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        listType,
        isValid,
      },
    };
  }
);

export default function DynamicListPage({ listType, isValid }: ListPageProps) {
  if (!isValid) {
    return (
      <ErrorPage
        variant="notFound"
        title="Entity type not found"
        description={`The entity type "${listType}" does not exist.`}
        showHomeButton
        showBackButton={false}
      />
    );
  }

  const entityConfig = getEntityConfig(listType);

  return (
    <GenericListPage
      entityConfig={entityConfig}
      entitySlug={listType}
    />
  );
}
