# Generated by Django 3.1.3 on 2021-04-28 11:20

from django.db import migrations, models
import django.db.models.deletion
# import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('i_want', models.TextField(blank=True, null=True)),
                ('so_that', models.TextField(blank=True, null=True)),
                ('story_points', models.SmallIntegerField(blank=True, null=True)),
                ('impact_on_business', models.SmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('headline', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('expected_result', models.TextField(blank=True, null=True)),
                ('actual_result', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Work to fix', 'Work to fix'), ('Immediate', 'Immediate'), ('High', 'High'), ('Medium', 'Medium'), ('Work it in', 'Work it in')], default='Work to fix', max_length=25)),
                ('type', models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], default='Bug Report', max_length=15)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('WIP', 'WIP'), ('Testing', 'Testing'), ('Fixed', 'Fixed'), ('Signed-Off', 'Signed-Off'), ('Clarify', 'Clarify'), ('Archived', 'Archived'), ('Deployed', 'Deployed')], default='Unassigned', max_length=15)),
                ('reported_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reported_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('screenshot_drive_link', models.UUIDField(blank=True, null=True)),
                ('os', models.CharField(choices=[('MacOS', 'MacOS'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Android', 'Android')], max_length=20)),
                ('browser', models.CharField(choices=[('Safari', 'Safari'), ('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('Brave', 'Brave')], max_length=20)),
                ('hours_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_fixed', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('estimated_start_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HLR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('template', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('start_date_time', models.DateTimeField()),
                ('days', models.SmallIntegerField()),
                ('goal', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('metrics', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('duration_estimate', models.SmallIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('duration_actual', models.SmallIntegerField(blank=True, null=True)),
                ('milestone', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completion_percent', models.SmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('week_start', models.CharField(blank=True, max_length=10, null=True)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('default_start_time', models.DateTimeField()),
                ('default_end_time', models.DateTimeField()),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('days_per_month', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('date_time_started', models.DateTimeField()),
                ('hours', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
                ('workcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.workcode')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('percentage_time', models.SmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.taskstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.tasktype'),
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.role')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SprintBug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('drive', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='HlrArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hlr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='hlr',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('organization', models.CharField(max_length=222)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug')),
            ],
        ),
        migrations.CreateModel(
            name='BugArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive', models.TextField()),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AddField(
            model_name='bug',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource'),
        ),
        migrations.AddField(
            model_name='bug',
            name='signed_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_off', to='a_pm_rapi.resource'),
        ),
        migrations.CreateModel(
            name='BacklogArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='backlog',
            name='as_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.persona'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='hlr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr'),
        ),
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
