# Generated by Django 3.1.3 on 2021-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
