# Generated by Django 3.1.3 on 2021-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0002_auto_20210503_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='screenshot_drive_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
