# Generated by Django 3.1.3 on 2021-07-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0004_auto_20210707_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hlr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr'),
        ),
    ]
