# Generated by Django 3.1.3 on 2021-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0005_task_hlr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugartifact',
            name='company',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='company',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
