# Generated by Django 3.1.3 on 2021-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0007_auto_20210716_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'default_manager_name': 'objects', 'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='backlogartifact',
            name='company',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlogartifact',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlogartifact',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlrartifact',
            name='company',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlrartifact',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlrartifact',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
