# Generated by Django 3.1.3 on 2021-08-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0008_auto_20210727_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-date_created']},
        ),
    ]
