# Generated by Django 3.1.3 on 2021-09-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0009_auto_20210804_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='project',
        ),
        migrations.AddField(
            model_name='persona',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
    ]
