# Generated by Django 3.1.3 on 2021-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0010_auto_20210902_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
