# Generated by Django 3.1.3 on 2021-09-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0011_auto_20210904_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
    ]
