# Generated by Django 3.1.3 on 2021-09-08 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0012_auto_20210906_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sprint',
            new_name='SprintMeta',
        ),
        migrations.RenameModel(
            old_name='SprintBug',
            new_name='SprintMetaBug',
        ),
        migrations.CreateModel(
            name='TestsConducted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('date_tested', models.DateField(blank=True, null=True)),
                ('tested_by', models.UUIDField(blank=True, null=True)),
                ('posted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('acceptance_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.acceptancecriteria')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskBug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskBacklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
