# Generated by Django 3.1.3 on 2021-09-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0013_auto_20210908_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('sprint_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprintmeta')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprint'),
            preserve_default=False,
        ),
    ]
