# Generated by Django 3.1.3 on 2021-09-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0014_auto_20210908_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsconducted',
            old_name='posted',
            new_name='passed',
        ),
        migrations.RemoveField(
            model_name='acceptancecriteria',
            name='task',
        ),
        migrations.AddField(
            model_name='acceptancecriteria',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog'),
        ),
    ]
