# Generated by Django 3.1.3 on 2021-09-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0015_auto_20210914_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptanceCriteria',
            new_name='AcceptanceTest',
        ),
    ]
