# Generated by Django 3.1.3 on 2021-09-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0016_auto_20210914_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
