# Generated by Django 3.1.3 on 2021-09-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0017_auto_20210914_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetest',
            name='given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='then',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='when',
            field=models.TextField(blank=True, null=True),
        ),
    ]
