# Generated by Django 3.1.3 on 2021-09-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0018_auto_20210914_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprintmeta',
            old_name='start_date_time',
            new_name='started',
        ),
    ]
