# Generated by Django 3.1.3 on 2021-09-22 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0019_auto_20210916_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbacklog',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog', unique=True),
        ),
    ]
