# Generated by Django 3.1.3 on 2021-10-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0020_auto_20210922_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statueses', to='a_pm_rapi.taskstatus'),
        ),
    ]
