# Generated by Django 3.1.3 on 2021-10-11 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0021_auto_20211007_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
    ]
