# Generated by Django 3.1.3 on 2021-10-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0022_auto_20211011_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_date_time',
            new_name='started',
        ),
    ]
