# Generated by Django 3.1.3 on 2021-10-14 08:43

import a_pm_rapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0023_auto_20211011_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={},
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(a_pm_rapi.models.get_unassigned_status), related_name='statueses', to='a_pm_rapi.taskstatus'),
        ),
    ]
