# Generated by Django 3.1.3 on 2021-10-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0025_auto_20211014_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sequence',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('name', 'project')},
        ),
    ]
