# Generated by Django 3.1.3 on 2021-10-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0026_auto_20211020_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_date_time',
            new_name='started',
        ),
    ]
