# Generated by Django 3.1.3 on 2021-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0027_auto_20211025_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='type',
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
