# Generated by Django 3.1.3 on 2021-10-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0028_auto_20211028_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_project', to='a_pm_rapi.project'),
        ),
    ]
