# Generated by Django 3.1.3 on 2021-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0029_auto_20211028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
