# Generated by Django 3.1.3 on 2021-11-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0030_auto_20211028_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbacklog',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog'),
        ),
        migrations.AlterUniqueTogether(
            name='taskbacklog',
            unique_together={('task', 'backlog')},
        ),
    ]
