# Generated by Django 3.1.3 on 2021-11-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0031_auto_20211101_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='impact_on_business',
            new_name='impact',
        ),
    ]
