# Generated by Django 3.1.3 on 2021-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0032_auto_20211108_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
