# Generated by Django 3.1.3 on 2021-11-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0033_backlog_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintmeta',
            name='project',
        ),
    ]
