# Generated by Django 3.1.3 on 2021-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0034_remove_sprintmeta_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beta_partners',
            field=models.BooleanField(default=False),
        ),
    ]
