# Generated by Django 3.1.3 on 2021-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0035_project_beta_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=7),
        ),
    ]
