# Generated by Django 3.1.3 on 2021-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0037_featurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acceptancetest',
            name='status',
            field=models.CharField(choices=[('To Test', 'To Test'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='To Test', max_length=7),
        ),
    ]
