# Generated by Django 3.1.3 on 2021-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0038_auto_20211203_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='beta_partners',
            field=models.BooleanField(default=False),
        ),
    ]
