# Generated by Django 3.1.3 on 2022-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0039_resource_beta_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetest',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
