# Generated by Django 3.1.3 on 2022-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0041_auto_20220322_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
