# Generated by Django 3.1.3 on 2022-03-23 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0042_auto_20220323_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmeta',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
