# Generated by Django 3.1.3 on 2022-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0043_sprintmeta_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintmeta',
            name='end_date',
        ),
        migrations.AddField(
            model_name='sprintmeta',
            name='sprint_to_generate',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
