# Generated by Django 3.1.3 on 2022-03-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0044_auto_20220324_1116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'project', 'company', 'parent_task')},
        ),
    ]
