# Generated by Django 4.0.3 on 2022-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0045_auto_20220330_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'project', 'company', 'parent_task'), name='Task And SubTask Unique'),
        ),
    ]
