# Generated by Django 3.2 on 2022-03-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0046_alter_task_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
