# Generated by Django 3.2 on 2022-03-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0047_alter_tasktype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_type_project', to='a_pm_rapi.project'),
        ),
    ]
