# Generated by Django 3.2 on 2022-04-02 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0049_auto_20220331_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rotting_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='rotting_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('WIP', 'WIP'), ('Testing', 'Testing'), ('Fixed', 'Fixed'), ('Signed-Off', 'Signed-Off'), ('Clarify', 'Clarify'), ('Archived', 'Archived'), ('Deployed', 'Deployed')], default='Unassigned', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='BugStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('rotting_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), (
                'Feature Request', 'Feature Request')], default='Bug Report', max_length=15),
        ),
    ]
