# Generated by Django 3.2 on 2022-04-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0050_auto_20220402_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_pm_rapi.bugstatus'),
        ),
    ]
