# Generated by Django 3.2 on 2022-04-04 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0051_alter_bug_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('rotting_days', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
    ]
