# Generated by Django 3.2 on 2022-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0054_alter_acceptancetest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], default='Bug Report', max_length=15),
        ),
    ]
