# Generated by Django 3.2 on 2022-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0055_bug_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('WIP', 'WIP'), ('Testing', 'Testing'), ('Fixed', 'Fixed'), ('Signed-Off', 'Signed-Off'), ('Clarify', 'Clarify'), ('Archived', 'Archived'), ('Deployed', 'Deployed')], default='Unassigned', max_length=15, null=True),
        ),
    ]
