# Generated by Django 3.2 on 2022-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0056_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancetest',
            name='status',
            field=models.CharField(choices=[('To Test', 'To Test'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='To Test', max_length=7, null=True),
        ),
    ]
