# Generated by Django 3.2 on 2022-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0059_auto_20220418_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.UUIDField(default='2c5a97cd-bc55-4015-b4a2-137be1559092'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('email', 'company'), name='email_company'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='user_company'),
        ),
    ]
