# Generated by Django 3.2 on 2022-04-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0060_auto_20220419_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(default='29c6ef53-ac7c-4c60-a03b-f0dfd2ec83a4', on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
            preserve_default=False,
        ),
    ]
