# Generated by Django 3.2 on 2022-04-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0061_auto_20220419_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_program', to='a_pm_rapi.program'),
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('name', 'program')},
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='project',
        ),
    ]
