# Generated by Django 3.2 on 2022-04-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0062_auto_20220419_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmeta',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
    ]
