# Generated by Django 3.2 on 2022-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0063_sprintmeta_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
