# Generated by Django 3.2 on 2022-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0064_bug_status_assigned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='status_assigned_date',
        ),
        migrations.AddField(
            model_name='task',
            name='status_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
