# Generated by Django 3.2 on 2022-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0065_auto_20220422_1432'),
    ]

    operations = [
    ]
