# Generated by Django 3.2 on 2022-04-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0066_auto_20220422_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='hours_estimate',
        ),
        migrations.AddField(
            model_name='bug',
            name='duration_actual',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='duration_estimate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='duration_unit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
