# Generated by Django 3.2 on 2022-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0067_auto_20220426_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('Weeks', 'Weeks'), ('Days', 'Days'), ('Hours', 'Hours'), ('Minutes', 'Minutes')], max_length=7, null=True),
        ),
    ]
