# Generated by Django 4.0.3 on 2022-04-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0068_alter_bug_duration_unit'),
    ]

    operations = [
    ]
