# Generated by Django 3.2 on 2022-05-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0069_merge_20220426_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancestatus',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='acceptancetest',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='headline',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_by_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bugstatus',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='hlr',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sprintmeta',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workcode',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
