# Generated by Django 3.2 on 2022-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0070_auto_20220506_1407'),
    ]

    operations = [
    ]
