# Generated by Django 3.2 on 2022-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0072_filler'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='person',
            field=models.UUIDField(null=True),
        ),
    ]
