# Generated by Django 3.2 on 2022-07-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0075_ina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ina',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ina',
            name='task_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.taskstatus'),
        ),
        migrations.AlterField(
            model_name='ina',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
    ]
