# Generated by Django 3.2 on 2022-07-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0076_auto_20220707_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INA',
        ),
    ]
