# Generated by Django 3.2 on 2022-07-08 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0077_delete_ina'),
    ]

    operations = [
        migrations.CreateModel(
            name='INA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('everyone_can_see_it', models.BooleanField(default=False)),
                ('anonymous_can_see_it', models.BooleanField(default=False)),
                ('everyone_in_object_company_can_see_it', models.BooleanField(default=True)),
                ('only_these_roles_can_see_it', models.JSONField(blank=True, null=True)),
                ('only_these_users_can_see_it', models.JSONField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('company', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.UUIDField()),
                ('model_name', models.TextField(editable=False)),
                ('microservice_name', models.TextField(editable=False)),
                ('record_id', models.UUIDField()),
                ('next_action', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=11)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
