# Generated by Django 3.2 on 2022-07-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0078_ina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ina',
            name='microservice_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ina',
            name='model_name',
            field=models.TextField(),
        ),
    ]
