# Generated by Django 3.2 on 2022-07-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0079_auto_20220708_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ina',
            name='responsible',
        ),
    ]
