# Generated by Django 3.2 on 2022-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0080_remove_ina_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ina',
            name='responsible',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
