# Generated by Django 3.2 on 2022-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0081_ina_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancestatus',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlogartifact',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugartifact',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugstatus',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlr',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlrartifact',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ina',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectartifact',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintmeta',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintmetabug',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbacklog',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbug',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskresource',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsconducted',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcode',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
