# Generated by Django 3.2 on 2022-08-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0082_auto_20220803_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_dependency', to='a_pm_rapi.task'),
        ),
    ]
