# Generated by Django 3.2 on 2022-08-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0087_auto_20220812_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_predecessor', to='a_pm_rapi.task'),
        ),
    ]
