# Generated by Django 3.2 on 2022-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0088_task_predecessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
