# Generated by Django 3.1.3 on 2022-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0089_auto_20220816_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
