# Generated by Django 3.1.3 on 2023-01-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0091_auto_20230121_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('Bug Report', 'Bug Report'), ('Feature Request', 'Feature Request')], default='Bug Report', max_length=15),
        ),
    ]
