# Generated by Django 3.1.3 on 2023-01-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0092_auto_20230121_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_type_program', to='a_pm_rapi.program'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('name', 'program')},
        ),
    ]
