# Generated by Django 3.1.3 on 2023-01-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0093_auto_20230121_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='project',
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task_type_program', to='a_pm_rapi.program'),
            preserve_default=False,
        ),
    ]
