# Generated by Django 3.1.3 on 2023-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0094_auto_20230121_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_event',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_event_do_what',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
