# Generated by Django 3.1.3 on 2023-01-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0095_auto_20230122_1845'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(name='me'), fields=('name', 'created_by'), name='one_me_program'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(name='me'), fields=('name', 'program', 'created_by'), name='one_me_project'),
        ),
    ]
