# Generated by Django 3.1.3 on 2023-01-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0096_auto_20230125_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
            preserve_default=False,
        ),
    ]
