# Generated by Django 4.0.3 on 2023-02-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0098_auto_20230207_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
    ]
