# Generated by Django 4.0.3 on 2023-02-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0099_alter_project_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancetest',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='as_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.persona'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='hlr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr'),
        ),
        migrations.AlterField(
            model_name='backlogartifact',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='signed_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_off', to='a_pm_rapi.resource'),
        ),
        migrations.AlterField(
            model_name='bugartifact',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug'),
        ),
        migrations.AlterField(
            model_name='bugcomment',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='hlr',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='hlrartifact',
            name='hlr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
        migrations.AlterField(
            model_name='projectartifact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprintmeta'),
        ),
        migrations.AlterField(
            model_name='sprintmeta',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
        migrations.AlterField(
            model_name='sprintmetabug',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug'),
        ),
        migrations.AlterField(
            model_name='sprintmetabug',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprintmeta'),
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprint'),
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.role'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_dependency', to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hlr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.hlr'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_predecessor', to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.tasktype'),
        ),
        migrations.AlterField(
            model_name='taskbacklog',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.backlog'),
        ),
        migrations.AlterField(
            model_name='taskbacklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='taskbug',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.bug'),
        ),
        migrations.AlterField(
            model_name='taskbug',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='taskresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource'),
        ),
        migrations.AlterField(
            model_name='taskresource',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_program', to='a_pm_rapi.program'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type_program', to='a_pm_rapi.program'),
        ),
        migrations.AlterField(
            model_name='testsconducted',
            name='acceptance_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.acceptancetest'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.resource'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.task'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='workcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.workcode'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project'),
        ),
    ]
