# Generated by Django 3.1.3 on 2023-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0102_auto_20230316_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ina',
            old_name='begin',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='ina',
            name='end',
        ),
        migrations.AddField(
            model_name='ina',
            name='event',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
