# Generated by Django 3.1.3 on 2023-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0103_auto_20230408_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='browser',
            field=models.CharField(choices=[('Edge', 'Edge'), ('Safari', 'Safari'), ('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('Brave', 'Brave')], max_length=20),
        ),
    ]
