# Generated by Django 3.1.3 on 2023-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0104_auto_20230614_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('Weeks', 'Weeks'), ('Days', 'Days'), ('Hours', 'Hours'), ('Minutes', 'Minutes')], max_length=7, null=True),
        ),
    ]
