# Generated by Django 3.1.3 on 2023-09-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0105_auto_20230704_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
    ]
