# Generated by Django 3.1.3 on 2023-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0106_auto_20230905_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='organization',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
