# Generated by Django 3.1.3 on 2023-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0107_auto_20230927_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('WIP', 'WIP'), ('Testing', 'Testing'), ('Fixed', 'Fixed'), ('Awaiting Staging Deployment', 'Awaiting Staging Deployment'), ('Awaiting Production Deployment', 'Awaiting Production Deployment'), ('Clarify', 'Clarify'), ('Archived', 'Archived')], default='Unassigned', max_length=30, null=True),
        ),
    ]
