# Generated by Django 3.1.3 on 2023-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0108_auto_20231002_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Clarify', 'Clarify'), ('WIP', 'WIP'), ('Testing', 'Testing'), ('Awaiting Staging Deployment', 'Awaiting Staging Deployment'), ('Awaiting Production Deployment', 'Awaiting Production Deployment'), ('Fixed', 'Fixed'), ('Archived', 'Archived')], default='Unassigned', max_length=30, null=True),
        ),
    ]
