# Generated by Django 3.1.3 on 2023-10-12 09:33

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0109_auto_20231003_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rrule',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
