# Generated by Django 3.1.3 on 2023-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0110_task_rrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
