# Generated by Django 3.1.3 on 2023-10-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0111_auto_20231013_1248'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='Task And SubTask Unique',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('order', 'name', 'project', 'client', 'parent_task'), name='Task And SubTask Unique'),
        ),
    ]
