# Generated by Django 3.1.3 on 2023-10-14 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0112_auto_20231013_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMetaProject',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('everyone_can_see_it', models.BooleanField(default=False)),
                ('anonymous_can_see_it', models.BooleanField(default=False)),
                ('everyone_in_object_company_can_see_it', models.BooleanField(default=True)),
                ('only_these_roles_can_see_it', models.JSONField(blank=True, null=True)),
                ('only_these_users_can_see_it', models.JSONField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('client', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_tags', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.project')),
                ('sprint_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.sprintmeta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
