# Generated by Django 3.1.3 on 2023-10-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0113_sprintmetaproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='final_stage',
            field=models.BooleanField(default=False),
        ),
    ]
