# Generated by Django 3.1.3 on 2023-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0114_taskstatus_final_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
