# Generated by Django 3.1.3 on 2023-10-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0115_taskstatus_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='color',
            new_name='colour',
        ),
    ]
