# Generated by Django 3.1.3 on 2023-10-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0116_auto_20231021_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
