# Generated by Django 3.1.3 on 2023-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0117_auto_20231021_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
