# Generated by Django 3.1.3 on 2023-11-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0119_auto_20231102_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_project', to='a_pm_rapi.project'),
        ),
    ]
