# Generated by Django 3.1.3 on 2023-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0120_taskstatus_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('name', 'project')},
        ),
    ]
