# Generated by Django 3.1.3 on 2023-11-08 12:05

import a_pm_rapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0121_auto_20231108_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_project', to='a_pm_rapi.project'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_type_project', to='a_pm_rapi.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(a_pm_rapi.models.get_unassigned_status), related_name='task_statuses', to='a_pm_rapi.taskstatus'),
        ),
    ]
