# Generated by Django 3.1.3 on 2023-11-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0122_auto_20231108_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('name', 'project')},
        ),
    ]
