# Generated by Django 3.1.3 on 2023-11-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0123_auto_20231108_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_pm_rapi.program'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_type_program', to='a_pm_rapi.program'),
        ),
    ]
