# Generated by Django 3.1.3 on 2023-11-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0124_auto_20231114_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together=set(),
        ),
    ]
