# Generated by Django 3.1.3 on 2023-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0127_auto_20231125_0827'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='Task And SubTask Unique',
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
