# Generated by Django 3.1.3 on 2023-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0128_auto_20231127_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptancestatus',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='acceptancetest',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='backlog',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='backlogartifact',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='bugartifact',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='bugcomment',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='bugstatus',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='featurerequest',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='hlr',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='hlrartifact',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='ina',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='projectartifact',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='sprintmeta',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='sprintmetabug',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='sprintmetaproject',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='sprinttask',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='taskbacklog',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='taskbug',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='taskresource',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='taskstatus',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='tasktype',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='testsconducted',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='workcode',
            old_name='template',
            new_name='_template',
        ),
        migrations.RenameField(
            model_name='workingtime',
            old_name='template',
            new_name='_template',
        ),
        migrations.AddField(
            model_name='acceptancestatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backlogartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlr',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hlrartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ina',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintmeta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintmetabug',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintmetaproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbacklog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskbug',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskresource',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsconducted',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
