# Generated by Django 3.1.3 on 2024-01-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0129_auto_20231127_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Clarify', 'Clarify'), ('WIP', 'WIP'), ('Ready for Testing', 'Ready for Testing'), ('Testing', 'Testing'), ('Awaiting Staging Deployment', 'Awaiting Staging Deployment'), ('Staging Review', 'Staging Review'), ('Awaiting Production Deployment', 'Awaiting Production Deployment'), ('Production Review', 'Production Review'), ('Failed Testing', 'Failed Testing'), ('Fixed', 'Fixed'), ('Archived', 'Archived')], default='Unassigned', max_length=30, null=True),
        ),
    ]
