# Generated by Django 3.1.3 on 2024-05-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0130_auto_20240101_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='a_pm_rapi.taskstatus'),
        ),
    ]
