# Generated by Django 3.1.3 on 2025-01-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0131_taskstatus_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resource',
            name='email_client',
        ),
        migrations.RemoveConstraint(
            model_name='resource',
            name='user_client',
        ),
    ]
