# Generated by Django 3.1.3 on 2025-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0132_auto_20250120_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_session',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
