# Generated by Django 5.2.5 on 2025-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0133_auto_20250410_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Clarify', 'Clarify'), ('WIP', 'WIP'), ('Failed Testing', 'Failed Testing'), ('Ready for Testing', 'Ready for Testing'), ('Testing', 'Testing'), ('Awaiting Staging Deployment', 'Awaiting Staging Deployment'), ('Staging Review', 'Staging Review'), ('Awaiting Production Deployment', 'Awaiting Production Deployment'), ('Production Review', 'Production Review'), ('Fixed', 'Fixed'), ('Archived', 'Archived')], default='Unassigned', max_length=30, null=True),
        ),
    ]
