# Generated by Django 5.2.5 on 2025-12-07 10:33

from django.db import migrations


def migrate_statuses_forward(apps, schema_editor):
    Bug = apps.get_model('a_pm_rapi', 'Bug')

    # Status mapping: old -> new
    # Note: Archived is kept as-is (not mapped)
    status_mapping = {
        'Ready for Testing': 'Ready for Sandbox Testing',
        'Testing': 'Ready for Sandbox Testing',
        'Awaiting Staging Deployment': 'Awaiting Sandbox Deploy',
        'Staging Review': 'Ready for Sandbox Testing',
        'Awaiting Production Deployment': 'Awaiting Prod Deploy',
        'Production Review': 'Ready for Prod Testing',
    }

    for old_status, new_status in status_mapping.items():
        Bug.objects.filter(status=old_status).update(status=new_status)


def migrate_statuses_backward(apps, schema_editor):
    Bug = apps.get_model('a_pm_rapi', 'Bug')

    # Reverse mapping: new -> old
    status_mapping = {
        'Awaiting Sandbox Deploy': 'Awaiting Staging Deployment',
        'Ready for Sandbox Testing': 'Staging Review',
        'Awaiting Prod Deploy': 'Awaiting Production Deployment',
        'Ready for Prod Testing': 'Production Review',
    }

    for new_status, old_status in status_mapping.items():
        Bug.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0134_add_labels_to_bug'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_backward),
    ]
