# Generated by Django 5.2.5 on 2026-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_pm_rapi', '0136_sync_bug_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='browser',
            field=models.CharField(blank=True, choices=[('Edge', 'Edge'), ('Safari', 'Safari'), ('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('Brave', 'Brave')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='os',
            field=models.CharField(blank=True, choices=[('MacOS', 'MacOS'), ('iOS', 'iOS'), ('Windows', 'Windows'), ('Android', 'Android')], max_length=20, null=True),
        ),
    ]
